# Generated by Django 5.2.5 on 2025-09-14 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests_app', '0002_requeststatus_color_requeststatus_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='الكلمة المفتاحية')),
                ('response', models.TextField(verbose_name='الرد')),
                ('action_type', models.CharField(choices=[('info', 'معلومات'), ('suggest_request', 'اقتراح طلب'), ('check_status', 'فحص حالة'), ('help', 'مساعدة')], default='info', max_length=50, verbose_name='نوع الإجراء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'رد البوت',
                'verbose_name_plural': 'ردود البوت',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'غرفة الدردشة',
                'verbose_name_plural': 'غرف الدردشة',
            },
        ),
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_title', models.CharField(max_length=200, verbose_name='العنوان المقترح')),
                ('suggested_description', models.TextField(verbose_name='الوصف المقترح')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('created', 'تم الإنشاء'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('user_approved', models.BooleanField(default=False, verbose_name='موافقة المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='requests_app.request', verbose_name='الطلب')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='chat_app.chatroom', verbose_name='غرفة الدردشة')),
            ],
            options={
                'verbose_name': 'طلب دردشة',
                'verbose_name_plural': 'طلبات الدردشة',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'رسالة مستخدم'), ('bot', 'رد تلقائي'), ('admin', 'رد إداري'), ('system', 'رسالة نظام')], default='user', max_length=10, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='محتوى الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_app.chatroom', verbose_name='غرفة الدردشة')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['created_at'],
            },
        ),
    ]
