# Generated by Django 5.2.5 on 2025-09-14 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='محتوى الرسالة')),
                ('message_type', models.CharField(choices=[('admin', 'إداري'), ('admin_urgent', 'إداري عاجل'), ('admin_info', 'معلومات إدارية'), ('admin_help', 'مساعدة إدارية')], default='admin', max_length=20, verbose_name='نوع الرسالة')),
                ('is_read_by_user', models.BooleanField(default=False, verbose_name='تم قراءته من المستخدم')),
                ('is_important', models.BooleanField(default=False, verbose_name='مهم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المدير')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to='chat_app.chatroom', verbose_name='غرفة الدردشة')),
            ],
            options={
                'verbose_name': 'رسالة إدارية',
                'verbose_name_plural': 'الرسائل الإدارية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_message', 'رسالة جديدة'), ('urgent_message', 'رسالة عاجلة'), ('complaint', 'شكوى'), ('request_created', 'طلب جديد'), ('user_help', 'طلب مساعدة')], default='new_message', max_length=20, verbose_name='نوع الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('priority', models.IntegerField(default=1, verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat_app.chatroom', verbose_name='غرفة الدردشة')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.message', verbose_name='الرسالة')),
            ],
            options={
                'verbose_name': 'إشعار دردشة',
                'verbose_name_plural': 'إشعارات الدردشة',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
