# Generated by Django 5.2.5 on 2025-11-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='الرقم القومي'),
        ),
    ]
