# Generated by Django 5.2.5 on 2025-11-14 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14, verbose_name='الرقم القومي')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الطلب (اختياري)')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات المشرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_password_resets', to=settings.AUTH_USER_MODEL, verbose_name='المشرف المعالج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب استعادة كلمة المرور',
                'verbose_name_plural': 'طلبات استعادة كلمة المرور',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_passw_created_26a77c_idx'), models.Index(fields=['status'], name='users_passw_status_9a95a4_idx')],
            },
        ),
    ]
