# Generated by Django 5.2.5 on 2025-08-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_remove_achievement_image_achievementimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
