# Generated by Django 5.2.5 on 2025-10-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_achievement_village'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='area',
            field=models.CharField(choices=[('السادات', 'السادات'), ('منوف', 'منوف'), ('سرس الليان', 'سرس الليان')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='village',
            field=models.CharField(blank=True, choices=[('مدينة منوف', 'مدينة منوف'), ('طملاي', 'طملاي'), ('شبشير طملاي', 'شبشير طملاي'), ('برهيم و منشأة سدود', 'برهيم و منشأة سدود'), ('جزي', 'جزي'), ('منشأة غمرين', 'منشأة غمرين'), ('بالمشط', 'بالمشط'), ('كفر السنابسه', 'كفر السنابسه'), ('صنصفط', 'صنصفط'), ('دمليج', 'دمليج'), ('زاوية رزين', 'زاوية رزين'), ('سدود', 'سدود'), ('بهواش', 'بهواش'), ('كمشوش', 'كمشوش'), ('فيشا الكبري', 'فيشا الكبري'), ('كفر فيشا الكبري', 'كفر فيشا الكبري'), ('هيت', 'هيت'), ('سروهيت', 'سروهيت'), ('دبركي', 'دبركي'), ('غمرين', 'غمرين'), ('تتا', 'تتا'), ('منشأة سلطان', 'منشأة سلطان'), ('سنجرج', 'سنجرج'), ('شبرا بلوله', 'شبرا بلوله'), ('كفر شبرا بلوله', 'كفر شبرا بلوله'), ('الحامول', 'الحامول'), ('كفر العامره', 'كفر العامره'), ('كفر رماح', 'كفر رماح'), ('ميت ربيعه', 'ميت ربيعه'), ('مدينة السادات', 'مدينة السادات'), ('كفر داوود', 'كفر داوود'), ('السلام', 'السلام'), ('الطرانه', 'الطرانه'), ('الاخماس', 'الاخماس'), ('الجيار', 'الجيار'), ('الخطاطبة البلد', 'الخطاطبة البلد'), ('الخطاطبة المحطه', 'الخطاطبة المحطه'), ('ابو نشابه', 'ابو نشابه'), ('عدنان المدني', 'عدنان المدني')], db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['area', 'village'], name='achievement_area_c24a08_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['-created_at'], name='achievement_created_07dca5_idx'),
        ),
    ]
