# Generated by Django 5.2.5 on 2025-10-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_alter_achievement_options_alter_achievement_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementimage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='achievementimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='achievementimage',
            name='image',
            field=models.ImageField(blank=True, help_text='سيتم تحسين الصورة تلقائياً', null=True, upload_to='achievements/%Y/%m/%d/'),
        ),
        migrations.AddIndex(
            model_name='achievementimage',
            index=models.Index(fields=['achievement', 'created_at'], name='achievement_achieve_d41c1a_idx'),
        ),
    ]
