# Generated by Django 5.2.5 on 2025-11-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_alter_achievement_area_alter_achievement_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='sectors',
            field=models.JSONField(blank=True, default=list, help_text='القطاعات التي ينتمي لها الإنجاز'),
        ),
    ]
