# Generated by Django 5.2.5 on 2025-11-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_achievement_sectors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='achievementimage',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='achievement',
            name='achievement_created_07dca5_idx',
        ),
        migrations.RemoveIndex(
            model_name='achievementimage',
            name='achievement_achieve_d41c1a_idx',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='achievementimage',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='achievementimage',
            name='image',
            field=models.ImageField(blank=True, help_text='سيتم تحسين الصورة تلقائياً', null=True, upload_to='achievements/images/'),
        ),
        migrations.AddIndex(
            model_name='achievementimage',
            index=models.Index(fields=['achievement'], name='achievement_achieve_95279d_idx'),
        ),
    ]
