# Generated by Django 5.2.5 on 2025-08-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststatus',
            name='color',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='لون الحالة'),
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الحالة'),
        ),
    ]
