# Generated by Django 5.2.5 on 2025-11-01 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='التاريخ')),
                ('total_visits', models.IntegerField(default=0, verbose_name='إجمالي الزيارات')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='الزوار الفريدون')),
                ('registered_users', models.IntegerField(default=0, verbose_name='المستخدمون المسجلون')),
                ('guest_visitors', models.IntegerField(default=0, verbose_name='الزوار الضيوف')),
            ],
            options={
                'verbose_name': 'إحصائية يومية',
                'verbose_name_plural': 'الإحصائيات اليومية',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الزيارة')),
                ('page_visited', models.CharField(blank=True, max_length=500, verbose_name='الصفحة المزارة')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='مفتاح الجلسة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'زائر',
                'verbose_name_plural': 'الزوار',
                'ordering': ['-visit_date'],
                'indexes': [models.Index(fields=['-visit_date'], name='admin_dashb_visit_d_8148ee_idx'), models.Index(fields=['ip_address'], name='admin_dashb_ip_addr_cf09d0_idx'), models.Index(fields=['session_key'], name='admin_dashb_session_48ad94_idx')],
            },
        ),
    ]
